coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: 30%
        threshold: 10%
        informational: true

ignore:
  - "vendor/**"
  - "**/*_test.go"
  - "**/test_utils.go"
  - "**/mock_*.go"
  - "pkg/monitoring/**"
