apiVersion: v1
kind: Service
metadata:
  name: colonies-service 
  labels:
    app: colonies
spec:
  selector:
    app: colonies
  ports:
    - name: http
      protocol: TCP
      port: 50070
      targetPort: 50070
