apiVersion: apps/v1
kind: Deployment
metadata:
  name: colonies-deployment
  labels:
    app: colonies
spec:
  replicas: {{ (int .Values.ColoniesServerReplicas) }}
  selector:
    matchLabels:
      app: colonies
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 25%
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: colonies
  template:
     metadata:
       labels:
          app: colonies
     spec:
       initContainers:
       - name: setupdb 
         image: {{ .Values.ColoniesServerImage | quote }}
         imagePullPolicy: "Always"
         command: ["/bin/colonies", "database", "create"]
         envFrom:
           - configMapRef:
               name: colonies-config
       containers:
       - name: colonies
         image: {{ .Values.ColoniesServerImage | quote }}
         imagePullPolicy: "Always"
         ports:
           - containerPort: 50070
         envFrom:
           - configMapRef:
               name: colonies-config
         resources:
          limits:
            cpu: {{ (.Values.ColoniesServerCPU | quote) }}
            memory: {{ (.Values.ColoniesServerMemory | quote) }}
          requests:
            cpu: {{ (.Values.ColoniesServerCPU | quote) }}
            memory: {{ (.Values.ColoniesServerMemory | quote) }}
