apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
     metadata:
       labels:
          app: postgres
     spec:
         containers:
           - name: timescaledb
             image: {{ (.Values.DBImage) }} 
             imagePullPolicy: "IfNotPresent"
             ports:
               - containerPort: 5432
             envFrom:
               - configMapRef:
                   name: postgres-config
             volumeMounts:
               - mountPath: /var/lib/postgresql
                 name: postgresdb
             resources:
                limits:
                  cpu: {{ (.Values.DBCPU | quote) }} 
                  memory: {{ (.Values.DBMemory | quote) }}
                requests:
                  cpu: {{ (.Values.DBCPU | quote) }} 
                  memory: {{ (.Values.DBMemory | quote) }}
         volumes:
           - name: postgresdb
             persistentVolumeClaim:
               claimName: db-storage-pvc
