apiVersion: v1
kind: ConfigMap
metadata:
  name: colonies-config
  labels:
    app: colonies
data:
  SERVERID: 9289dfccedf27392810b96968535530bb69f90afe7c35738e0e627f3810d943e
  SERVERPORT: 8080
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: rFcLGNkgsNtksg6Pgtn9CumL4xXBQ7
  VERBOSE: true

